name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run area test
      run: npm run area

    - name: Run refactoring test
      run: npm run functional

    - name: Run cucumber
      run: npm run cucumber

    - name: Run unit tests
      run: npm run test:jest